package AML.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class App_SubstituteMenu extends SubstituteMenuBase {
  public App_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for App. Generated from implicit smart reference attribute.", new SNodePointer("r:8f6b9f4d-1e5b-4c8f-a071-dbe1371a4767(AML.structure)", "1624465643280654124")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_u5o6fv_a(), CONCEPTS.App$v2));
    result.add(new SMP_Subconcepts_u5o6fv_b());
    return result;
  }

  public class SMP_ReferenceScope_u5o6fv_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_u5o6fv_a() {
      super(CONCEPTS.App$v2, LINKS.init_state$ixix, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_u5o6fv_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_u5o6fv_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "App", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.App$v2);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept App$v2 = MetaAdapterFactory.getConcept(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e55191df2cL, "AML.structure.App");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink init_state$ixix = MetaAdapterFactory.getReferenceLink(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e55191df2cL, 0x168b42e5519beaf2L, "init_state");
  }
}
