package AML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_STATUS extends EnumerationDescriptorBase {

  public EnumerationDescriptor_STATUS() {
    super(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519beacaL, "STATUS", "r:8f6b9f4d-1e5b-4c8f-a071-dbe1371a4767(AML.structure)/1624465643281312458");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_true_0 = new EnumerationDescriptor.MemberDescriptor("true", "high", 0x168b42e5519beacbL, "r:8f6b9f4d-1e5b-4c8f-a071-dbe1371a4767(AML.structure)/1624465643281312459");
  private final EnumerationDescriptor.MemberDescriptor myMember_false_0 = new EnumerationDescriptor.MemberDescriptor("false", "low", 0x168b42e5519beaccL, "r:8f6b9f4d-1e5b-4c8f-a071-dbe1371a4767(AML.structure)/1624465643281312460");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519beacaL, 0x168b42e5519beacbL, 0x168b42e5519beaccL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_true_0, myMember_false_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "true":
        return myMember_true_0;
      case "false":
        return myMember_false_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
