package AML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int Actuator = 1;
  public static final int App = 2;
  public static final int Brick = 3;
  public static final int Sensor = 4;
  public static final int State = 5;
  public static final int Transition = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L);
    builder.put(0x168b42e5519bead1L, Action);
    builder.put(0x168b42e55191df31L, Actuator);
    builder.put(0x168b42e55191df2cL, App);
    builder.put(0x168b42e55191df2dL, Brick);
    builder.put(0x168b42e55191df32L, Sensor);
    builder.put(0x168b42e5519bea42L, State);
    builder.put(0x168b42e5519beacdL, Transition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
