package AML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptActuator = createDescriptorForActuator();
  /*package*/ final ConceptDescriptor myConceptApp = createDescriptorForApp();
  /*package*/ final ConceptDescriptor myConceptBrick = createDescriptorForBrick();
  /*package*/ final ConceptDescriptor myConceptSensor = createDescriptorForSensor();
  /*package*/ final ConceptDescriptor myConceptState = createDescriptorForState();
  /*package*/ final ConceptDescriptor myConceptTransition = createDescriptorForTransition();
  /*package*/ final EnumerationDescriptor myEnumerationSTATUS = new EnumerationDescriptor_STATUS();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptActuator, myConceptApp, myConceptBrick, myConceptSensor, myConceptState, myConceptTransition);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.Actuator:
        return myConceptActuator;
      case LanguageConceptSwitch.App:
        return myConceptApp;
      case LanguageConceptSwitch.Brick:
        return myConceptBrick;
      case LanguageConceptSwitch.Sensor:
        return myConceptSensor;
      case LanguageConceptSwitch.State:
        return myConceptState;
      case LanguageConceptSwitch.Transition:
        return myConceptTransition;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationSTATUS);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AML", "Action", 0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519bead1L);
    b.class_(false, false, false);
    b.origin("r:8f6b9f4d-1e5b-4c8f-a071-dbe1371a4767(AML.structure)/1624465643281312465");
    b.version(3);
    b.property("status", 0x168b42e5519bead2L).type(MetaIdFactory.dataTypeId(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519beacaL)).origin("1624465643281312466").done();
    b.associate("actuator", 0x168b42e5519bead3L).target(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e55191df31L).optional(false).origin("1624465643281312467").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActuator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AML", "Actuator", 0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e55191df31L);
    b.class_(false, false, false);
    // extends: AML.structure.Brick
    b.super_(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e55191df2dL);
    b.origin("r:8f6b9f4d-1e5b-4c8f-a071-dbe1371a4767(AML.structure)/1624465643280654129");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForApp() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AML", "App", 0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e55191df2cL);
    b.class_(false, false, true);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8f6b9f4d-1e5b-4c8f-a071-dbe1371a4767(AML.structure)/1624465643280654124");
    b.version(3);
    b.associate("init_state", 0x168b42e5519beaf2L).target(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519bea42L).optional(false).origin("1624465643281312498").done();
    b.aggregate("bricks", 0x168b42e55191df33L).target(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e55191df2dL).optional(true).ordered(true).multiple(true).origin("1624465643280654131").done();
    b.aggregate("state", 0x168b42e5519beaf1L).target(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519bea42L).optional(false).ordered(true).multiple(true).origin("1624465643281312497").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBrick() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AML", "Brick", 0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e55191df2dL);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8f6b9f4d-1e5b-4c8f-a071-dbe1371a4767(AML.structure)/1624465643280654125");
    b.version(3);
    b.property("pin", 0x168b42e55191df2fL).type(PrimitiveTypeId.INTEGER).origin("1624465643280654127").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AML", "Sensor", 0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e55191df32L);
    b.class_(false, false, false);
    // extends: AML.structure.Brick
    b.super_(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e55191df2dL);
    b.origin("r:8f6b9f4d-1e5b-4c8f-a071-dbe1371a4767(AML.structure)/1624465643280654130");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForState() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AML", "State", 0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519bea42L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8f6b9f4d-1e5b-4c8f-a071-dbe1371a4767(AML.structure)/1624465643281312322");
    b.version(3);
    b.aggregate("actions", 0x168b42e5519bea44L).target(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519bead1L).optional(true).ordered(true).multiple(true).origin("1624465643281312324").done();
    b.aggregate("transitions", 0x168b42e5519bea45L).target(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519beacdL).optional(false).ordered(true).multiple(false).origin("1624465643281312325").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AML", "Transition", 0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519beacdL);
    b.class_(false, false, false);
    b.origin("r:8f6b9f4d-1e5b-4c8f-a071-dbe1371a4767(AML.structure)/1624465643281312461");
    b.version(3);
    b.property("status", 0x168b42e5519beaceL).type(MetaIdFactory.dataTypeId(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519beacaL)).origin("1624465643281312462").done();
    b.associate("sensor", 0x168b42e5519beacfL).target(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e55191df32L).optional(false).origin("1624465643281312463").done();
    b.associate("target", 0x168b42e5519bead0L).target(0x292b2b71dc8d4e66L, 0x9cdade3a826a9e55L, 0x168b42e5519bea42L).optional(false).origin("1624465643281312464").done();
    return b.create();
  }
}
